<a href="https://colab.research.google.com/github/ollin02/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy: Análisis numérico eficiente con Python**

NumPy es una biblioteca de Python que ofrece diversas herramientas y funcionalidades esenciales para la computación científica, incluyendo objetos de matriz multidimensional conocidos como *arrays*, rutinas para operaciones rápidas en matrizes, además de operaciones matemáticas, manipulación de formas, estadística entre otros. Es ampliamente utilizada en áreas como análisis de datos, procesamiento de señales y aprendizaje de máquina.

Para acceder a la documentación de esta biblioteca, puedes hacer clic en el siguiente enlace: https://numpy.org/devdocs/index.html

In [1]:
import numpy as np

ano_inicial = 2002
ano_final = 2102
np.arange(ano_inicial, ano_final, 4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098])

In [4]:
ano_inicial = 2002
ano_final = 2102
np.arange(ano_inicial, ano_final + 1, 4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098, 2102])

In [2]:
ano_inicial = 2002
ano_final = 2102
np.arange(ano_inicial, ano_final + 1, 4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098, 2102])

In [3]:
ano_inicial = 2000
ano_final = 2102
np.arange(ano_inicial, ano_final, 4)

array([2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036, 2040,
       2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076, 2080, 2084,
       2088, 2092, 2096, 2100])